spec:
  inputs:
    ghc_version:
    package:
    pre_deploy_command:
      default: "true"
    stack_options:
      default: --system-ghc

---

include:
  - inputs:
      package: $[[ inputs.package ]]
    remote:
      "https://raw.githubusercontent.com/danieljtrowbridge/hs-config/main\
      /gitlab-ci/lint.yaml"
  - inputs:
      ghc_version: $[[ inputs.ghc_version ]]
      package: $[[ inputs.package ]]
      pre_deploy_command: $[[ inputs.pre_deploy_command ]]
      stack_options: $[[ inputs.stack_options ]]
    remote:
      "https://raw.githubusercontent.com/danieljtrowbridge/hs-config/main\
      /gitlab-ci/pages.yaml"
  - inputs:
      ghc_version: $[[ inputs.ghc_version ]]
      package: $[[ inputs.package ]]
      stack_options: $[[ inputs.stack_options ]]
    remote:
      "https://raw.githubusercontent.com/danieljtrowbridge/hs-config/main\
      /gitlab-ci/test.yaml"
