spec:
  inputs:
    ghc_version:
    package:
    pre_deploy_command:
      default: "true"
    stack_options:
      default: --system-ghc

---

pages:
  artifacts:
    paths:
      - public/
  image: haskell:$[[ inputs.ghc_version ]]
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - >-
      stack $[[ inputs.stack_options ]] haddock
      --haddock-arguments "-o public/" --no-haddock-deps $[[ inputs.package ]]
    - mv $[[ inputs.package ]]/public/ .
    - $[[ inputs.command ]]
  stage: deploy
