---

name: CI

on:
  workflow_call:
    inputs:
      ghc-version:
        required: true
        type: string
      package:
        required: true
        type: string

jobs:
  lint:
    name: Lint ${{ inputs.package }}
    uses: danieljtrowbridge/hs-config/.github/workflows/lint.yaml@main
    with:
      docker-tag: ${{ inputs.ghc-version }}
      package: ${{ inputs.package }}
  yamllint:
    name: Run yamllint
    uses: danieljtrowbridge/hs-config/.github/workflows/yamllint.yaml@main
  test:
    name: Test ${{ inputs.package }}
    uses: danieljtrowbridge/hs-config/.github/workflows/test.yaml@main
    with:
      ghc-version: ${{ inputs.ghc-version }}
      package: ${{ inputs.package }}
