---

name: Deploy documentation

on:
  workflow_call:
    inputs:
      ghc-version:
        required: true
        type: string
      os:
        default: ubuntu-latest
        required: false
        type: string
      package:
        required: true
        type: string

jobs:
  build:
    name: Build ${{ inputs.package }} documentation
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          ghc-version: ${{ inputs.ghc-version }}
          stack-setup-ghc: true
      - name: Restore Stack root directory
        uses: actions/cache@v3
        with:
          key: stack-root
          path: .stack-root/
      - name: Restore ${{ inputs.package }} dependencies
        uses: actions/cache@v3
        with:
          key: ${{ inputs.package }}-stack-work
          path: .stack-work/
      - name: Build ${{ inputs.package }} documentation
        run: >-
          stack haddock --haddock-arguments "-o public/" --no-haddock-deps
          ${{ inputs.package }}
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ${{ inputs.package }}/public/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    name: Deploy ${{ inputs.package }} documentation to GitHub Pages
    needs:
      - build
    permissions:
      id-token: write
      pages: write
    runs-on: ${{ inputs.os }}
    steps:
      - id: deploy
        name: Deploy
        uses: actions/deploy-pages@v2
