---

name: Test

on:
  workflow_call:
    inputs:
      ghc-version:
        required: true
        type: string
      package:
        required: true
        type: string
      os:
        default: ubuntu-latest
        required: false
        type: string

jobs:
  test:
    name: Test ${{ inputs.package }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Stack
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          ghc-version: ${{ inputs.ghc-version }}
          stack-setup-ghc: true
      - name: Run ${{ inputs.package }} test suites
        run: stack test ${{ inputs.package }}
