---

name: Test

on:
  workflow_call:
    inputs:
      ghc-version:
        required: true
        type: string
      os:
        default: ubuntu-latest
        required: false
        type: string
      package:
        required: true
        type: string

jobs:
  test:
    env:
      STACK_ROOT: ${{ github.workspace }}/.stack-root
    name: Test ${{ inputs.package }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Restore Stack root directory
        uses: actions/cache@v3
        with:
          key: stack-root
          path: .stack-root/
      - name: Restore ${{ inputs.package }} dependencies
        uses: actions/cache@v3
        with:
          key: ${{ inputs.package }}-stack-work
          path: .stack-work/
      - name: Set up Stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          ghc-version: ${{ inputs.ghc-version }}
          stack-no-global: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run ${{ inputs.package }} test suites
        run: stack --system-ghc test ${{ inputs.package }}
