---

name: Test

on:
  workflow_call:
    inputs:
      cabal-artifact-name:
        required: false
        type: string
      cabal-artifact-path:
        required: false
        type: string
      ghc-version:
        required: true
        type: string
      os:
        default: ubuntu-latest
        required: false
        type: string
      package:
        required: true
        type: string

jobs:
  test:
    env:
      STACK_ROOT: ${{ github.workspace }}/.stack-root
    name: Test ${{ inputs.package }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Stack
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          ghc-version: ${{ inputs.ghc-version }}
          stack-setup-ghc: true
      - name: Restore Stack root directory
        uses: actions/cache@v3
        with:
          key: stack-root
          path: .stack-root/
      - name: Restore ${{ inputs.package }} dependencies
        uses: actions/cache@v3
        with:
          key: ${{ inputs.package }}-stack-work
          path: .stack-work/
      - name: Run ${{ inputs.package }} test suites
        run: stack test ${{ inputs.package }}
      - if: inputs.cabal-artifact-name
        name: Upload ${{ inputs.package }}.cabal
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.cabal-artifact-name }}
          path: >-
            ${{
            inputs.cabal-artifact-path
            ||
            format('{0}/{0}.cabal', inputs.package)
            }}
