---

name: Run yamllint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

jobs:
  yamllint:
    name: Run yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install yamllint
        run: |
          apt-get update
          apt-get install -y yamllint
      - name: Check YAML formatting
        run: yamllint .
